### ISSUE TITLE
Need a reference

### ISSUE THREAD

**Issue by BaptisteVandecrux** [jasonebox/GCNet_photogrammetry#1]
To refer to this package in a publication I need it to go public and that we agree on a citation. 
I think it is fine to leave the pictures on it anyway as they are all public domain anyway.

I suggest
Box, J.E, Ravheim, M,  GC-Net photogrammetry python package, https://github.com/jasonebox/GCNet_photogrammetry  2020
for citation?

**Comment by BaptisteVandecrux** [comment]
Hi Jason,
Would it be ok to make that repo public?
Thanks

**Comment by jasonebox** [comment]
yes on both questions

**Comment by BaptisteVandecrux** [comment]
Since you own the repo, you need to go into the Setting tab and at the bottom to change the repo's visibility.

**Comment by jasonebox** [comment]
is public now
